# Generated by Django 3.2.7 on 2021-10-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facebook', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_google', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, default='', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_fb_user', models.BooleanField(default=False)),
                ('is_google_user', models.BooleanField(default=False)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('suggested_predict', models.CharField(default='', max_length=250)),
                ('n_status', models.CharField(max_length=1)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
