# Generated by Django 3.2.7 on 2021-10-19 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20211001_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='n_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
