# Generated by Django 3.2.7 on 2021-10-19 00:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(default=datetime.datetime(2021, 10, 18, 19, 44, 0, 350728))),
            ],
        ),
        migrations.CreateModel(
            name='UserInstitutionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.file')),
                ('user_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.userinstitution')),
            ],
        ),
    ]
