# Generated by Django 3.2.7 on 2021-10-22 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='file',
            name='url_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
