# Generated by Django 3.2.7 on 2021-10-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20211022_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
