# Generated by Django 3.2.7 on 2021-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20211022_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstitution',
            name='n_status',
            field=models.IntegerField(default=1),
        ),
    ]
