# Generated by Django 3.2.7 on 2021-10-19 00:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('creation', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(default=datetime.datetime.now)),
                ('final_date', models.DateField(default=datetime.datetime.now)),
                ('recomendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.recomendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('creation', models.DateField(default=datetime.datetime.now)),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.typetransaction')),
                ('user_institution_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.userinstitutionfile')),
            ],
        ),
    ]
