# Generated by Django 3.2.7 on 2021-10-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20211023_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='have_extra_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.category'),
        ),
    ]
