# Generated by Django 3.2.7 on 2021-10-23 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_userinstitution_n_status'),
        ('detail', '0004_auto_20211023_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.categoryclass')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.report')),
            ],
        ),
        migrations.CreateModel(
            name='DetailFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSubfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('category_title', models.IntegerField(choices=[(0, 'NO ASSIGN '), (1, 'Capital Contribuido'), (2, 'Capital Ganado')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='have_extra_info',
            new_name='have_sub_detail',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='detail',
        ),
        migrations.AddField(
            model_name='detail',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detail',
            name='type_movement',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feature',
            name='have_sub_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_subtotal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_banorte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_bbva',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_santander',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportinstitution',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.report'),
        ),
        migrations.DeleteModel(
            name='FeatureReport',
        ),
        migrations.AddField(
            model_name='subfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.feature'),
        ),
        migrations.AddField(
            model_name='subdetail',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.detail'),
        ),
        migrations.AddField(
            model_name='detailsubfeature',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.detail'),
        ),
        migrations.AddField(
            model_name='detailsubfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.subfeature'),
        ),
        migrations.AddField(
            model_name='detailfeature',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.detail'),
        ),
        migrations.AddField(
            model_name='detailfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.feature'),
        ),
        migrations.AddField(
            model_name='feature',
            name='category_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detail.categoryclass'),
        ),
    ]
