# Generated by Django 3.2.7 on 2021-10-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_auto_20211023_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryclass',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
