# Generated by Django 3.2.7 on 2021-10-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_auto_20211023_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subfeature',
            old_name='feature',
            new_name='subfeature',
        ),
        migrations.AlterField(
            model_name='detail',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
