# Generated by Django 3.2.7 on 2021-10-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0009_alter_detail_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsubfeature',
            old_name='feature',
            new_name='subfeature',
        ),
    ]
