# Generated by Django 3.2.7 on 2021-10-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0010_rename_feature_detailsubfeature_subfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subfeature',
            old_name='subfeature',
            new_name='feature',
        ),
    ]
